config/routes.rb
LibraryMongo::Application.routes.draw do
  get 'writers/sync/' => 'writers#sync'

  resources :writers

  resources :tests

  

  

end

app/models/test.rb
class Test
  include Mongoid::Document
  field :name, type: String
end

app/models/writer.rb
class Writer
  include Mongoid::Document
  field :code, type: String
  field :name, type: String
  field :book, type: String
  field :address, type: String
  field :line, type:Integer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test }
      else
        format.html { render action: 'new' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name)
    end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: [:show, :edit, :update, :destroy]

  # GET /writers
  # GET /writers.json
  def index
    @writers = Writer.where(name: Regexp.new(params[:name] ? params[:name]+".*" : "") ,
                            book: Regexp.new(params[:book] ? params[:book]+".*" : "") ,
                            code: Regexp.new(params[:code] ? params[:code]+".*" : "") ,
                            address: Regexp.new(params[:address] ? params[:address]+".*" : "") ,
      ).order_by(:line.asc).paginate(:page => params[:page], :limit => 15)
  end

  def sync
    #Clear objects on Database
    Writer.destroy_all
    
    directory = "public"
    path_data = File.join(directory, "dados.txt")
    counter = 1
    File.open(path_data, "r") do |f|    
      while (line = f.gets)
        @w = Writer.create({:code => line[0..6] ,:book=> line[7..51].strip ,
          :name=>line[52..80].strip ,:address=>line[81..86].strip, :line=>counter})
        counter += 1
      end
    end
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
  end

  # GET /writers/new
  def new
    @writer = Writer.new
  end

  # GET /writers/1/edit
  def edit
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, notice: 'Writer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @writer }
      else
        format.html { render action: 'new' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writers/1
  # PATCH/PUT /writers/1.json
  def update
    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to @writer, notice: 'Writer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer.destroy
    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writer
      @writer = Writer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def writer_params
      params.require(:writer).permit(:name, :book, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/layouts/application.html.haml
%html{:lang => 'en'}<>
  %head
    %meta{charset: "utf-8"}/
    %title LibraryMongo
    = stylesheet_link_tag :application, :media => "all"
    = csrf_meta_tags
  %body{"data-controller" => "#{controller.controller_name}", "data-action" => "#{controller.action_name}"}
    = yield
  = javascript_include_tag :application

app/views/writers/_form.html.haml
= form_for @writer do |f|
  - if @writer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@writer.errors.count, "error")} prohibited this writer from being saved:"
      %ul
        - @writer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :book
    = f.text_field :book
  .field
    = f.label :address
    = f.number_field :address
  .actions
    = f.submit 'Save'

app/views/writers/edit.html.haml
%h1 Editing writer

= render 'form'

= link_to 'Show', @writer
\|
= link_to 'Back', writers_path

app/views/writers/index.html.haml
%h1 Listing writers

= form_tag("writers", method: "get") do
  = label_tag(:code, "Código:")
  = text_field_tag(:code)
  %br
  = label_tag(:name, "Name:")
  = text_field_tag(:name)
  %br
  = label_tag(:book, "Book:")
  = text_field_tag(:book)
  %br
  = label_tag(:address, "Address:")
  = text_field_tag(:address)
  %br
  = submit_tag("Search")

%table
  %tr
    %th Code
    %th Name
    %th Book
    %th Address
    %th File line
    %th
    %th
    %th

  - @writers.each do |writer|
    %tr
      %td= writer.code
      %td= writer.name
      %td= writer.book
      %td= writer.address
      %td= writer.line
      %td= link_to 'Show', writer
      %td= link_to 'Edit', edit_writer_path(writer)
      %td= link_to 'Destroy', writer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
= will_paginate @writers
= link_to 'New Writer', new_writer_path

app/views/writers/new.html.haml
%h1 New writer

= render 'form'

= link_to 'Back', writers_path

app/views/writers/show.html.haml
%p#notice= notice
%p
  %b Code:
  = @writer.code
%p
  %b Name:
  = @writer.name
%p
  %b Book:
  = @writer.book
%p
  %b Address:
  = @writer.address
%p
  %b File Line:
  = @writer.line

= link_to 'Edit', edit_writer_path(@writer)
\|
= link_to 'Back', writers_path

app/views/writers/sync.html.haml
%p#notice= notice

%p
  %b Syncronização efetuada com sucesso
= link_to 'Back', writers_path